" ウインドウにタイトルを表示する
set title
" 行番号を表示
set number
" エンコーディングをutf-8に設定
set encoding=utf-8
" 検索語句のハイライト
set hlsearch
" ルーラーの表示
set ruler
" 構文毎に文字色を変化
syntax on
" タブ入力を複数の空白入力に置き換える
set expandtab
" タブ文字の幅
set tabstop=4
" 自動インデントでずれる幅
set shiftwidth=4
" 改行時に前の行のインデントを継続する
set autoindent
" 改行時に入力された行の末尾に合わせて次の行のインデントを指定する
set smartindent
